name: ci
# GitHub Actions?

on: [push, pull_request]

jobs:
    testa:
        runs-on: ubuntu-latest
        steps: 
            - name: Baixar o codigo
              uses: actions/checkout@v4

            - name: Instalar Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.12"
            
            - name: Instalar dependencias
              run: pip3 install -r req.txt

            - name: Rodar testes
              run: pytest -v
